# https://pre-commit.com/index.html#adding-pre-commit-plugins-to-your-project
repos:
  # https://github.com/editorconfig-checker/editorconfig-checker.python?tab=readme-ov-file#usage-with-the-pre-commit-git-hooks-framework
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.0"
    hooks:
      - id: editorconfig-checker

  # https://github.com/DavidAnson/markdownlint-cli2#pre-commit
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2

  # https://github.com/mrtazz/checkmake#pre-commit-usage
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        alias: checkmake
        exclude: .*[.]mk$
        name: checkmake [Makefile]
      - id: checkmake
        alias: checkmake-module
        exclude: Makefile$
        name: checkmake [Makefile includes]
        args:
        - --config=.checkmake-module.ini

  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace

  # https://github.com/shellcheck-py/shellcheck-py#as-a-pre-commit-hook
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
